name: Build

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup npm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install X server
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Install the dependencies
        run: npm clean-install && npm run postinstall

      - name: Build package
        run: npm run esbuild

      - name: Test language server
        run: npm run test:server

      - name: Test language server client
        run: |
          Xvfb -ac :99 -screen 0 1280x1024x16 &
          export DISPLAY=:99
          npm run test:e2e

      - name: Package Extension
        run: npx vsce package

      - name: Archive vsix package
        uses: actions/upload-artifact@v4
        with:
          name: modelica-language-server.vsix
          path: modelica-language-server-*.vsix

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: modelica-language-server.vsix

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            modelica-language-server-*.vsix
          fail_on_unmatched_files: true
          generate_release_notes: true
          append_body: true
