name: Build

on:
  push:
    branches:
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup npm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install the dependencies
        run: npm clean-install && npm run postinstall

      - name: Build package
        run: npm run compile

      - name: Test language server
        run: npm run test:server

      - name: Package Extension
        run: npx vsce package

      - name: Archive vsix package
        uses: actions/upload-artifact@v4
        with:
          name: language-server-modelica.vsix
          path: language-server-modelica-*.vsix

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: language-server-modelica.vsix

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            language-server-modelica-*.vsix
          fail_on_unmatched_files: true
          generate_release_notes: true
          append_body: true
